#!/bin/bash
TARGET='public_ftp/incoming'
SOURCE='fake/'  
lftp -f "
open csrv11.aname.net
user buezdgna `security find-generic-password -a ${USER} -s misshosting_ftp -w`
mirror --reverse --delete --verbose $SOURCE $TARGET
bye
"
